name: Docker Image build and Push to DO Registry

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Prep things for doing doctl stuff
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
            token: ${{ secrets.DO_TOKEN }}

      - name: Login to registry
        run: doctl registry login

      - name: Pull code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Check old blog checkout
        run: ls -al old-blog

      - name: Build and push old-blog image
        run: ./old-blog/build.sh

