name: Docker Image build and Push to DO Registry

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Prep things for doing doctl stuff
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
            token: ${{ secrets.DO_TOKEN }}

      # Do not create permanent tokens 
      - name: Login to registry
        run: doctl registry login --expiry-seconds 600 

      - name: Pull code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
            # The only private repo here was removed.
            #          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Build and publish submodule projects
        run: make ci

