name: Docker Image build and Push to DO Registry

on:
  push:
    branches:
      - master

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - run: ls -al old-blog
      - run: ./old-blog/build.sh

